name: Hello world workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "Hello world"